### ISSUE TITLE
Bug: Blue buttons to always have white text

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#18]
### Describe the bug

Make the text on the button white to increase the contrast and improves the visibility.

### Screenshots

![image](https://user-images.githubusercontent.com/13496774/92409277-f68aac80-f137-11ea-9967-dfdafa765cd7.png)

**Comment by a-developer-and-her-mac** [comment]
Is this the button in Speak.razor? If so, I'll try to take on this issue for Hacktoberfest.

**Comment by a-developer-and-her-mac** [comment]
Oh, never mind, I think somebody else fixed this.. You might want to close this issue.

**Comment by pjgpetecodes** [comment]
Hi @a-developer-and-her-mac .. I don't think it has been fixed... The site can be found here... 

[.NET Notts - New Site](https://dotnetnotts.azurewebsites.net/speak)

Would you like to be assigned?

**Comment by a-developer-and-her-mac** [comment]
Sure, I'll give it a try.

**Comment by wordshaker** [comment]
All issues tagged with hacktoberfest labels are expected to be done in October 😄 Take your time with it

**Comment by atharvakadlag** [comment]
@pjgpetecodes The issue has now been fixed the pull request is ready to be merged without any conflict

**Comment by hansaj-sharma** [comment]
i think the issue is not fixed on the website, can i make a pull Request?

**Comment by wordshaker** [comment]
Hi @hansaj-sharma Please do 😄

**Comment by wordshaker** [comment]
Completed by @atharvakadlag
